version: 2
gpu: &gpu
  machine:
    image: ubuntu-1604:201903-01
  resource_class: gpu.small

jobs:
  python_lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: setup
          command: |
              sudo pip install black "isort[pyproject]" numpy --progress-bar off
      - run:
          name: run black
          command: |
              black . --diff
              black . --check
      - run:
          name: run isort
          command: |
              isort --version
              isort -rc . --diff
              isort -rc . --check-only

  install_and_test_ubuntu:
    <<: *gpu
    steps:
      - checkout
      - run:
          name: Install dependencies
          no_output_timeout: 20m
          command: |
              sudo apt-get update || true
              sudo apt-get install -y --no-install-recommends \
                  build-essential \
                  git \
                  curl \
                  vim \
                  ca-certificates \
                  pkg-config \
                  wget \
                  zip \
                  unzip || true

      - run:
          name: Test PointNav 2020 submission
          command: |
              git clone https://github.com/facebookresearch/habitat-challenge.git
              cd habitat-challenge
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce
              apt-cache policy docker-ce

              curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
              distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
              curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
                sudo tee /etc/apt/sources.list.d/nvidia-docker.list
              sudo apt-get update
              sudo apt-get install nvidia-docker2
              sudo pkill -SIGHUP dockerd

              docker build . --file Pointnav.Dockerfile -t pointnav_submission
              ./test_locally_pointnav_rgbd.sh --docker-name pointnav_submission

              pip install "evalai>=1.2.3"

              # Set EvalAI account token
              evalai set_token $EVALAI_TOKEN


              # Push docker image to EvalAI docker registry
              # Pointnav
              evalai push pointnav_submission:latest --phase habitat20-pointnav-minival

workflows:
  version: 2
  install_and_test:
    jobs:
      - python_lint
      - install_and_test_ubuntu
